---

apiVersion: v1
kind: Service
metadata:
  name: drone-master
  labels:
    app: drone-master
spec:
  type: ClusterIP
  selector:
    app: drone-master
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP

...
